//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab8.Models
{

    public partial class Comment
    {
        public int Id { get; set; }
        public string AutorName { get; set; }
        public string Comment1 { get; set; }
        public int IdPost { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
