//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab6
{
    using System.Collections.Generic;

    public partial class Buy
    {
        public Buy()
        {
            this.BuyMerchandises = new HashSet<BuyMerchandise>();
        }
    
        public int Идентификатор { get; set; }
        public System.DateTime Date { get; set; }
        public int Client_Идентификатор { get; set; }
        public int Discount_Идентификатор { get; set; }
    
        public virtual ICollection<BuyMerchandise> BuyMerchandises { get; set; }
        public virtual Client Client { get; set; }
        public virtual Discount Discount { get; set; }
    }
}
