//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab6
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class BuyersEntities : DbContext
    {
        public BuyersEntities()
            : base("name=BuyersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Buy> Buys { get; set; }
        public DbSet<BuyMerchandise> BuyMerchandises { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<Discount> Discounts { get; set; }
        public DbSet<Merchandise> Merchandises { get; set; }
    }
}
