//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab6
{
    using System.Collections.Generic;

    public partial class Merchandise
    {
        public Merchandise()
        {
            this.BuyMerchandises = new HashSet<BuyMerchandise>();
        }
    
        public int Идентификатор { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
    
        public virtual ICollection<BuyMerchandise> BuyMerchandises { get; set; }
    }
}
